import { SupportedLanguage } from '../types';

export const SUPPORTED_LANGUAGES: SupportedLanguage[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🌐' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', flag: '🇵🇰' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', flag: '🇮🇳' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', flag: '🇮🇳' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', flag: '🇳🇵' },
  { code: 'si', name: 'Sinhala', nativeName: 'සිංහල', flag: '🇱🇰' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'zh', name: 'Chinese (Simplified)', nativeName: '简体中文', flag: '🇨🇳' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', flag: '🇵🇱' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', flag: '🇸🇪' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', flag: '🇺🇦' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', flag: '🇬🇷' },
  { code: 'he', name: 'Hebrew', nativeName: 'עברית', flag: '🇮🇱' },
  { code: 'cs', name: 'Czech', nativeName: 'Čeština', flag: '🇨🇿' },
  { code: 'hu', name: 'Hungarian', nativeName: 'Magyar', flag: '🇭🇺' },
  { code: 'ro', name: 'Romanian', nativeName: 'Română', flag: '🇷🇴' },
];

export const UI_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    tagline: 'Understand the World. Beyond Search.',
    searchPlaceholder: 'Search anything across Past, Present, and Future...',
    searchButton: 'Search',
    allTab: 'All',
    websitesTab: 'Websites',
    appsTab: 'Apps',
    aiTab: 'AI Overview',
    timelineTab: 'Timeline',
    futureTab: 'Future Intelligence',
    imagesTab: 'Images',
    videosTab: 'Videos',
    newsTab: 'News',
    mapsTab: 'Maps & Places',
    shoppingTab: 'Shopping',
    researchTab: 'Research',
    translateTab: 'Translate',
    compareTab: 'Compare',
    askAi: 'Ask Follow-up',
    pastSection: 'PAST: Historical Foundation',
    presentSection: 'PRESENT: Live Facts & Developments',
    futureSection: 'FUTURE: Trends & Projections',
    demoNotice: 'Phase 1 Prototype: Demonstrating ANTIQORA search UI layout. Real web search indexes connect in Phase 2.',
    settings: 'Settings',
    profile: 'Profile',
    appearance: 'Appearance',
    searchSettings: 'Search Settings',
    languageRegion: 'Language & Region',
    safeSearch: 'Safe Search',
    privacy: 'Privacy & Data',
    notifications: 'Notifications',
    voiceSearch: 'Voice Search',
    aiSettings: 'AI Settings',
    searchResults: 'Search Results',
    accessibility: 'Accessibility',
    appPwa: 'App & PWA',
    about: 'About ANTIQORA',
    save: 'Save',
    cancel: 'Cancel',
    reset: 'Reset All Settings',
    clearAll: 'Clear All Data'
  },
  hi: {
    tagline: 'संसार को समझें। खोज से भी आगे।',
    searchPlaceholder: 'भूत, वर्तमान और भविष्य के पार कुछ भी खोजें...',
    searchButton: 'खोजें',
    allTab: 'सभी',
    websitesTab: 'वेबसाइटें',
    appsTab: 'ऐप्स',
    aiTab: 'एआई अवलोकन',
    timelineTab: 'समयरेखा',
    futureTab: 'भविष्य की जानकारी',
    imagesTab: 'चित्र',
    videosTab: 'वीडियो',
    newsTab: 'समाचार',
    mapsTab: 'स्थान और मानचित्र',
    shoppingTab: 'खरीदारी',
    researchTab: 'शोध',
    translateTab: 'अनुवाद',
    compareTab: 'तुलना',
    askAi: 'अनुवर्ती प्रश्न पूछें',
    pastSection: 'अतीत: ऐतिहासिक आधार',
    presentSection: 'वर्तमान: प्रत्यक्ष तथ्य और विकास',
    futureSection: 'भविष्य: रुझान और अनुमान',
    demoNotice: 'फेज 1 प्रोटोटाइप: एंटीकोरा खोज इंटरफ़ेस प्रदर्शन।',
    settings: 'सेटिंग्स',
    profile: 'प्रोफ़ाइल',
    appearance: 'दिखावट',
    searchSettings: 'खोज सेटिंग्स',
    languageRegion: 'भाषा और क्षेत्र',
    safeSearch: 'सुरक्षित खोज',
    privacy: 'गोपनीयता और डेटा',
    notifications: 'सूचनाएं',
    voiceSearch: 'आवाज़ खोज',
    aiSettings: 'एआई सेटिंग्स',
    searchResults: 'खोज परिणाम',
    accessibility: 'अभिगम्यता',
    appPwa: 'ऐप और PWA',
    about: 'एंटीकोरा के बारे में',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    reset: 'सभी सेटिंग्स रीसेट करें',
    clearAll: 'सभी डेटा साफ़ करें'
  },
  ta: {
    tagline: 'உலகைப் புரிந்து கொள்ளுங்கள். தேடலுக்கு அப்பால்.',
    searchPlaceholder: 'கடந்த, நிகழ், எதிர்காலத் தகவல்களைத் தேடுங்கள்...',
    searchButton: 'தேடு',
    allTab: 'அனைத்தும்',
    websitesTab: 'வலைத்தளங்கள்',
    appsTab: 'செயலிகள்',
    aiTab: 'AI கண்ணோட்டம்',
    timelineTab: 'காலவரிசை',
    futureTab: 'எதிர்கால நுண்ணறிவு',
    imagesTab: 'படங்கள்',
    videosTab: 'வீடியோக்கள்',
    newsTab: 'செய்திகள்',
    mapsTab: 'இடங்கள்',
    shoppingTab: 'ஷாப்பிங்',
    researchTab: 'ஆராய்ச்சி',
    translateTab: 'மொழிபெயர்ப்பு',
    compareTab: 'ஒப்பிடு',
    askAi: 'தொடர் கேள்வி கேளுங்கள்',
    pastSection: 'கடந்த காலம்: வரலாற்று அடித்தளம்',
    presentSection: 'நிகழ்காலம்: நேரடி உண்மைகள்',
    futureSection: 'எதிர்காலம்: கணிப்புகள்',
    demoNotice: 'கட்டம் 1 முன்மாதிரி: ANTIQORA தேடல் இடைமுகம்.',
    settings: 'அமைப்புகள்',
    profile: 'சுயவிவரம்',
    appearance: 'தோற்றம்',
    searchSettings: 'தேடல் அமைப்புகள்',
    languageRegion: 'மொழி மற்றும் பகுதி',
    safeSearch: 'பாதுகாப்பான தேடல்',
    privacy: 'தனியுரிமை மற்றும் தரவு',
    notifications: 'அறிவிப்புகள்',
    voiceSearch: 'குரல் தேடல்',
    aiSettings: 'AI அமைப்புகள்',
    searchResults: 'தேடல் முடிவுகள்',
    accessibility: 'அணுகல்தன்மை',
    appPwa: 'செயலி & PWA',
    about: 'ANTIQORA பற்றி',
    save: 'சேமி',
    cancel: 'ரத்துசெய்',
    reset: 'அனைத்து அமைப்புகளையும் மீட்டமை',
    clearAll: 'அனைத்து தரவையும் அழி'
  },
  te: {
    tagline: 'ప్రపంచాన్ని అర్థం చేసుకోండి. అన్వేషణకు ఆవల.',
    searchPlaceholder: 'గతం, వర్తమానం, భవిష్యత్తులో ఏదైనా శోధించండి...',
    searchButton: 'శోధించండి',
    allTab: 'అన్నీ',
    websitesTab: 'వెబ్‌సైట్లు',
    appsTab: 'యాప్‌లు',
    aiTab: 'AI అవలోకనం',
    timelineTab: 'కాలక్రమం',
    futureTab: 'భవిష్యత్ మేధస్సు',
    imagesTab: 'చిత్రాలు',
    videosTab: 'వీడియోలు',
    newsTab: 'వార్తలు',
    mapsTab: 'ప్రాంతాలు',
    shoppingTab: 'షాపింగ్',
    researchTab: 'పరిశోధన',
    translateTab: 'అనువాదం',
    compareTab: 'పోల్చండి',
    askAi: 'ప్రశ్న అడగండి',
    pastSection: 'గతం: చారిత్రక పునాది',
    presentSection: 'వర్తమానం: ప్రత్యక్ష వాస్తవాలు',
    futureSection: 'భవిష్యత్తు: ధోరణులు',
    demoNotice: 'ఫేజ్ 1 ప్రొటోటైప్: ANTIQORA శోధన ఇంటర్‌ఫేస్.',
    settings: 'సెట్టింగ్‌లు',
    profile: 'ప్రొఫైల్',
    appearance: 'రూపురేఖలు',
    searchSettings: 'శోధన సెట్టింగ్‌లు',
    languageRegion: 'భాష & ప్రాంతం',
    safeSearch: 'సురక్షిత శోధన',
    privacy: 'గోప్యత & డేటా',
    notifications: 'నోటిఫికేషన్‌లు',
    voiceSearch: 'వాయిస్ శోధన',
    aiSettings: 'AI సెట్టింగ్‌లు',
    searchResults: 'శోధన ఫలితాలు',
    accessibility: 'సౌలభ్యం',
    appPwa: 'యాప్ & PWA',
    about: 'ANTIQORA గురించి',
    save: 'సేవ్ చేయండి',
    cancel: 'రద్దు చేయండి',
    reset: 'అన్ని సెట్టింగ్‌లను రీసెట్ చేయండి',
    clearAll: 'మొత్తం డేటాను క్లియర్ చేయండి'
  },
  kn: {
    tagline: 'ಜಗತ್ತನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ. ಶೋಧನೆಯಾಚೆಗೆ.',
    searchPlaceholder: 'ಭೂತ, ವರ್ತಮಾನ ಮತ್ತು ಭವಿಷ್ಯತ್ತಿನಲ್ಲಿ ಹುಡುಕಿ...',
    searchButton: 'ಹುಡುಕಿ',
    allTab: 'ಎಲ್ಲವೂ',
    websitesTab: 'ವೆಬ್‌ಸೈಟ್‌ಗಳು',
    appsTab: 'ಆ್ಯಪ್‌ಗಳು',
    aiTab: 'AI ಅವಲೋಕನ',
    timelineTab: 'ಸಮಯರೇಖೆ',
    futureTab: 'ಭವಿಷ್ಯದ ಒಳನೋಟ',
    imagesTab: 'ಚಿತ್ರಗಳು',
    videosTab: 'ವೀಡಿಯೊಗಳು',
    newsTab: 'ಸುದ್ದಿ',
    mapsTab: 'ಸ್ಥಳಗಳು',
    shoppingTab: 'ಶಾಪಿಂಗ್',
    researchTab: 'ಸಂಶೋಧನೆ',
    translateTab: 'ಅನುವಾದ',
    compareTab: 'ಹೋಲಿಸಿ',
    askAi: 'ಪ್ರಶ್ನೆ ಕೇಳಿ',
    pastSection: 'ಭೂತಕಾಲ: ಐತಿಹಾಸಿಕ ಅಡಿಪಾಯ',
    presentSection: 'ವರ್ತಮಾನ: ನೈಜ ಸಂಗತಿಗಳು',
    futureSection: 'ಭವಿಷ್ಯ: ಮುನ್ಸೂಚನೆಗಳು',
    demoNotice: 'ಹಂತ 1 ಮಾದರಿ: ANTIQORA ಶೋಧ ಇಂಟರ್‌ಫೇಸ್.',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    profile: 'ಪ್ರೊಫೈಲ್',
    appearance: 'ಗೋಚರತೆ',
    searchSettings: 'ಹುಡುಕಾಟ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    languageRegion: 'ಭಾಷೆ & ಪ್ರದೇಶ',
    safeSearch: 'ಸುರಕ್ಷಿತ ಹುಡುಕಾಟ',
    privacy: 'ಗೌಪ್ಯತೆ & ಡೇಟಾ',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    voiceSearch: 'ಧ್ವನಿ ಹುಡುಕಾಟ',
    aiSettings: 'AI ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    searchResults: 'ಹುಡುಕಾಟ ಫಲಿತಾಂಶಗಳು',
    accessibility: 'ಪ್ರವೇಶಿಸುವಿಕೆ',
    appPwa: 'ಆ್ಯಪ್ & PWA',
    about: 'ANTIQORA ಕುರಿತು',
    save: 'ಉಳಿಸಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    reset: 'ಎಲ್ಲಾ ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಮರುಹೊಂದಿಸಿ',
    clearAll: 'ಎಲ್ಲಾ ಡೇಟಾವನ್ನು ತೆರವುಗೊಳಿಸಿ'
  },
  ml: {
    tagline: 'ലോകത്തെ മനസ്സിലാക്കുക. തിരച്ചിലിനപ്പുറം.',
    searchPlaceholder: 'ഭൂതവും വർത്തമാനവും ഭാവിയും തിരയുക...',
    searchButton: 'തിരയുക',
    allTab: 'എല്ലാം',
    websitesTab: 'വെബ്സൈറ്റുകൾ',
    appsTab: 'ആപ്പുകൾ',
    aiTab: 'AI അവലോകനം',
    timelineTab: 'ടൈംലൈൻ',
    futureTab: 'ഭാവി കാഴ്ചപ്പാട്',
    imagesTab: 'ചിത്രങ്ങൾ',
    videosTab: 'വീഡിയോകൾ',
    newsTab: 'വാർത്തകൾ',
    mapsTab: 'സ്ഥലങ്ങൾ',
    shoppingTab: 'ഷോപ്പിംഗ്',
    researchTab: 'ഗവേഷണം',
    translateTab: 'വിവർത്തനം',
    compareTab: 'താരതമ്യം',
    askAi: 'ചോദ്യം ചോദിക്കുക',
    pastSection: 'ഭൂതകാലം: ചരിത്രപരമായ അടിത്തറ',
    presentSection: 'വർത്തമാനം: തത്സമയ വസ്തുതകൾ',
    futureSection: 'ഭാവി: നിരീക്ഷണങ്ങൾ',
    demoNotice: 'ഘട്ടം 1 പ്രോട്ടോടൈപ്പ്: ANTIQORA തിരയൽ ഇന്റർഫേസ്.',
    settings: 'ക്രമീകരണങ്ങൾ',
    profile: 'പ്രൊഫൈൽ',
    appearance: 'രൂപഭംഗി',
    searchSettings: 'തിരയൽ ക്രമീകരണങ്ങൾ',
    languageRegion: 'ഭാഷയും പ്രദേശവും',
    safeSearch: 'സുരക്ഷിത തിരയൽ',
    privacy: 'സ്വകാര്യതയും വിവരങ്ങളും',
    notifications: 'അറിയിപ്പുകൾ',
    voiceSearch: 'ശബ്ദ തിരയൽ',
    aiSettings: 'AI ക്രമീകരണങ്ങൾ',
    searchResults: 'തിരയൽ ഫലങ്ങൾ',
    accessibility: 'ആക്സസിബിലിറ്റി',
    appPwa: 'ആപ്പും PWA യും',
    about: 'ANTIQORA കുറിച്ച്',
    save: 'സംരക്ഷിക്കുക',
    cancel: 'റദ്ദാക്കുക',
    reset: 'എല്ലാ ക്രമീകരണങ്ങളും പുനഃസ്ഥാപിക്കുക',
    clearAll: 'എല്ലാ ഡാറ്റയും മായ്ക്കുക'
  },
  bn: {
    tagline: 'বিশ্বকে বুঝুন। অনুসন্ধানের ঊর্ধ্বে।',
    searchPlaceholder: 'অতীত, বর্তমান এবং ভবিষ্যতের যে কোনো কিছু খুঁজুন...',
    searchButton: 'অনুসন্ধান',
    allTab: 'সব',
    websitesTab: 'ওয়েবসাইট',
    appsTab: 'অ্যাপস',
    aiTab: 'এআই ওভারভিউ',
    timelineTab: 'টাইমলাইন',
    futureTab: 'ভবিষ্যত অন্তর্দৃষ্টি',
    imagesTab: 'ছবি',
    videosTab: 'ভিডিও',
    newsTab: 'সংবাদ',
    mapsTab: 'স্থান',
    shoppingTab: 'কেনাকাটা',
    researchTab: 'গবেষণা',
    translateTab: 'অনুবাদ',
    compareTab: 'তুলনা',
    askAi: 'প্রশ্ন করুন',
    pastSection: 'অতীত: ঐতিহাসিক ভিত্তি',
    presentSection: 'বর্তমান: বাস্তব তথ্য',
    futureSection: 'ভবিষ্যত: সম্ভাব্য দৃষ্টিভঙ্গি',
    demoNotice: 'ফেজ ১ প্রোটোটাইপ: ANTIQORA সার্চ ইন্টারফেস।',
    settings: 'সেটিংস',
    profile: 'প্রোফাইল',
    appearance: 'চেহারা',
    searchSettings: 'অনুসন্ধান সেটিংস',
    languageRegion: 'ভাষা ও অঞ্চল',
    safeSearch: 'নিরাপদ অনুসন্ধান',
    privacy: 'গোপনীয়তা ও ডেটা',
    notifications: 'বিজ্ঞপ্তি',
    voiceSearch: 'ভয়েস অনুসন্ধান',
    aiSettings: 'এআই সেটিংস',
    searchResults: 'অনুসন্ধানের ফলাফল',
    accessibility: 'অ্যাক্সেসযোগ্যতা',
    appPwa: 'অ্যাপ ও পিডব্লিউএ',
    about: 'ANTIQORA সম্পর্কে',
    save: 'সংরক্ষণ করুন',
    cancel: 'বাতিল করুন',
    reset: 'সব সেটিংস রিসেট করুন',
    clearAll: 'সব ডেটা মুছে ফেলুন'
  },
  mr: {
    tagline: 'जग समजून घ्या. शोधाच्या पलीकडे.',
    searchPlaceholder: 'भूतकाळ, वर्तमानकाळ आणि भविष्यकाळात शोधा...',
    searchButton: 'शोधा',
    allTab: 'सर्व',
    websitesTab: 'वेबसाइट्स',
    appsTab: 'अ‍ॅप्स',
    aiTab: 'AI विहंगावलोकन',
    timelineTab: 'टाइमलाइन',
    futureTab: 'भविष्यकालीन अंतर्दृष्टी',
    imagesTab: 'चित्रे',
    videosTab: 'व्हिडिओ',
    newsTab: 'बातम्या',
    mapsTab: 'ठिकाणे',
    shoppingTab: 'खरेदी',
    researchTab: 'संशोधन',
    translateTab: 'भाषांतर',
    compareTab: 'तुलना करा',
    askAi: 'पुढचा प्रश्न विचारा',
    pastSection: 'भूतकाळ: ऐतिहासिक पाया',
    presentSection: 'वर्तमान: थेट तथ्ये',
    futureSection: 'भविष्य: अंदाज',
    demoNotice: 'फेज 1 प्रोटोटाइप: ANTIQORA शोध इंटरफेस.',
    settings: 'सेटिंग्ज',
    profile: 'प्रोफाइल',
    appearance: 'दिसणे',
    searchSettings: 'शोध सेटिंग्ज',
    languageRegion: 'भाषा आणि प्रदेश',
    safeSearch: 'सुरक्षित शोध',
    privacy: 'गोपनीयता आणि डेटा',
    notifications: 'सूचना',
    voiceSearch: 'व्हॉइस सर्च',
    aiSettings: 'AI सेटिंग्ज',
    searchResults: 'शोध निकाल',
    accessibility: 'सुलભता',
    appPwa: 'अ‍ॅप आणि PWA',
    about: 'ANTIQORA बद्दल',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    reset: 'सर्व सेटिंग्ज रीसेट करा',
    clearAll: 'सर्व डेटा पुसून टाका'
  },
  gu: {
    tagline: 'વિશ્વને સમજો. શોધથી પણ આગળ.',
    searchPlaceholder: 'ભૂતકાળ, વર્તમાન અને ભવિષ્યમાં કંઈપણ શોધો...',
    searchButton: 'શોધો',
    allTab: 'બધું',
    websitesTab: 'વેબસાઇટ્સ',
    appsTab: 'એપ્સ',
    aiTab: 'AI ઝાંખી',
    timelineTab: 'ટાઇમલાઇન',
    futureTab: 'ભવિષ્યની દ્રષ્ટિ',
    imagesTab: 'છબીઓ',
    videosTab: 'વિડિઓઝ',
    newsTab: 'સમાચાર',
    mapsTab: 'સ્થળો',
    shoppingTab: 'ખરીદી',
    researchTab: 'સંશોધન',
    translateTab: 'અનુવાદ',
    compareTab: 'સરખામણી',
    askAi: 'પ્રશ્ન પૂછો',
    pastSection: 'ભૂતકાળ: ઐતિહાસિક પાયો',
    presentSection: 'વર્તમાન: વાસ્તવિક હકીકતો',
    futureSection: 'ભવિષ્ય: સંભાવનાઓ',
    demoNotice: 'તબક્કો 1 પ્રોટોટાઇપ: ANTIQORA સર્ચ ઇન્ટરફેસ.',
    settings: 'સેટિંગ્સ',
    profile: 'પ્રોફાઇલ',
    appearance: 'દેખાવ',
    searchSettings: 'શોધ સેટિંગ્સ',
    languageRegion: 'ભાષા અને પ્રદેશ',
    safeSearch: 'સુરક્ષિત શોધ',
    privacy: 'ગોપનીયતા અને ડેટા',
    notifications: 'સૂચનાઓ',
    voiceSearch: 'વોઇસ સર્ચ',
    aiSettings: 'AI સેટિંગ્સ',
    searchResults: 'શોધ પરિણામો',
    accessibility: 'સુલભતા',
    appPwa: 'એપ્લિકેશન અને PWA',
    about: 'ANTIQORA વિશે',
    save: 'સાચવો',
    cancel: 'રદ કરો',
    reset: 'બધા સેટિંગ્સ રીસેટ કરો',
    clearAll: 'બધો ડેટા સાફ કરો'
  },
  pa: {
    tagline: 'ਦੁਨੀਆ ਨੂੰ ਸਮਝੋ। ਖੋਜ ਤੋਂ ਪਰੇ।',
    searchPlaceholder: 'ਅਤੀਤ, ਵਰਤਮਾਨ ਅਤੇ ਭਵਿੱਖ ਵਿੱਚ ਕੁਝ ਵੀ ਖੋਜੋ...',
    searchButton: 'ਖੋਜੋ',
    allTab: 'ਸਭ',
    websitesTab: 'ਵੈੱਬਸਾਈਟਾਂ',
    appsTab: 'ਐਪਸ',
    aiTab: 'AI ਸੰਖੇਪ ਜਾਣਕਾਰੀ',
    timelineTab: 'ਸਮਾਂਰੇਖਾ',
    futureTab: 'ਭਵਿੱਖ ਦੀ ਸੂਝ',
    imagesTab: 'ਤਸਵੀਰਾਂ',
    videosTab: 'ਵੀਡੀਓ',
    newsTab: 'ਖ਼ਬਰਾਂ',
    mapsTab: 'ਸਥਾਨ',
    shoppingTab: 'ਖਰੀਦਦਾਰੀ',
    researchTab: 'ਖੋਜ',
    translateTab: 'ਅਨੁਵਾਦ',
    compareTab: 'ਤੁਲਨਾ ਕਰੋ',
    askAi: 'ਸਵਾਲ ਪੁੱਛੋ',
    pastSection: 'ਅਤੀਤ: ਇਤਿਹਾਸਕ ਨੀਂਹ',
    presentSection: 'ਵਰਤਮਾਨ: ਤਾਜ਼ਾ ਤੱਥ',
    futureSection: 'ਭਵਿੱਖ: ਅੰਦਾਜ਼ੇ',
    demoNotice: 'ਫੇਜ਼ 1 ਪ੍ਰੋਟੋਟਾਈਪ: ANTIQORA ਖੋਜ ਇੰਟਰਫੇਸ।',
    settings: 'ਸੈਟਿੰਗਾਂ',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    appearance: 'ਦਿੱਖ',
    searchSettings: 'ਖੋਜ ਸੈਟਿੰਗਾਂ',
    languageRegion: 'ਭਾਸ਼ਾ ਅਤੇ ਖੇਤਰ',
    safeSearch: 'ਸੁਰੱਖਿਅਤ ਖੋਜ',
    privacy: 'ਗੋਪਨੀਯਤਾ ਅਤੇ ਡਾਟਾ',
    notifications: 'ਸੂਚਨਾਵਾਂ',
    voiceSearch: 'ਆਵਾਜ਼ ਖੋਜ',
    aiSettings: 'AI ਸੈਟਿੰਗਾਂ',
    searchResults: 'ਖੋਜ ਨਤੀਜੇ',
    accessibility: 'ਪਹੁੰਚਯੋਗਤਾ',
    appPwa: 'ਐਪ ਅਤੇ PWA',
    about: 'ANTIQORA ਬਾਰੇ',
    save: 'ਸੰਭਾਲੋ',
    cancel: 'ਰੱਦ ਕਰੋ',
    reset: 'ਸਾਰੀਆਂ ਸੈਟਿੰਗਾਂ ਰੀਸੈਟ ਕਰੋ',
    clearAll: 'ਸਾਰਾ ਡਾਟਾ ਸਾਫ਼ ਕਰੋ'
  },
  ur: {
    tagline: 'دنیا کو سمجھیں۔ تلاش سے آگے۔',
    searchPlaceholder: 'ماضی، حال اور مستقبل میں کچھ بھی تلاش کریں...',
    searchButton: 'تلاش',
    allTab: 'سبھی',
    websitesTab: 'ویب سائٹس',
    appsTab: 'ایپس',
    aiTab: 'AI جائزہ',
    timelineTab: 'ٹائم لائن',
    futureTab: 'مستقبل کی بصیرت',
    imagesTab: 'تصاویر',
    videosTab: 'ویڈیوز',
    newsTab: 'خبریں',
    mapsTab: 'مقامات',
    shoppingTab: 'خریداری',
    researchTab: 'تحقیق',
    translateTab: 'ترجمہ',
    compareTab: 'موازنہ',
    askAi: 'مزید سوال پوچھیں',
    pastSection: 'ماضی: تاریخی بنیاد',
    presentSection: 'حال: تصدیق شدہ حقائق',
    futureSection: 'مستقبل: امکانات',
    demoNotice: 'مرحلہ 1 پروٹو ٹائپ: ANTIQORA سرچ انٹرفیس۔',
    settings: 'ترتیبات',
    profile: 'پروفائل',
    appearance: 'ظاہری شکل',
    searchSettings: 'تلاش کی ترتیبات',
    languageRegion: 'زبان اور خطہ',
    safeSearch: 'محفوظ تلاش',
    privacy: 'رازداری اور ڈیٹا',
    notifications: 'اطلاعات',
    voiceSearch: 'صوتی تلاش',
    aiSettings: 'AI ترتیبات',
    searchResults: 'تلاش کے نتائج',
    accessibility: 'رسائی',
    appPwa: 'ایپ اور PWA',
    about: 'ANTIQORA کے بارے میں',
    save: 'محفوظ کریں',
    cancel: 'منسوخ کریں',
    reset: 'تمام ترتیبات ری سیٹ کریں',
    clearAll: 'تمام ڈیٹا صاف کریں'
  },
  es: {
    tagline: 'Comprende el mundo. Más allá de la búsqueda.',
    searchPlaceholder: 'Busca cualquier tema en el Pasado, Presente y Futuro...',
    searchButton: 'Buscar',
    allTab: 'Todo',
    websitesTab: 'Sitios web',
    appsTab: 'Aplicaciones',
    aiTab: 'Resumen IA',
    timelineTab: 'Línea de tiempo',
    futureTab: 'Inteligencia Futura',
    imagesTab: 'Imágenes',
    videosTab: 'Videos',
    newsTab: 'Noticias',
    mapsTab: 'Lugares',
    shoppingTab: 'Compras',
    researchTab: 'Investigación',
    translateTab: 'Traducir',
    compareTab: 'Comparar',
    askAi: 'Preguntar seguimiento',
    pastSection: 'PASADO: Fundación Histórica',
    presentSection: 'PRESENTE: Hechos y Desarrollos Actuales',
    futureSection: 'FUTURO: Tendencias y Escenarios',
    demoNotice: 'Prototipo Fase 1: Demostración de interfaz ANTIQORA.',
    settings: 'Ajustes',
    profile: 'Perfil',
    appearance: 'Apariencia',
    searchSettings: 'Ajustes de búsqueda',
    languageRegion: 'Idioma y región',
    safeSearch: 'Búsqueda segura',
    privacy: 'Privacidad y datos',
    notifications: 'Notificaciones',
    voiceSearch: 'Búsqueda por voz',
    aiSettings: 'Ajustes de IA',
    searchResults: 'Resultados de búsqueda',
    accessibility: 'Accesibilidad',
    appPwa: 'App y PWA',
    about: 'Acerca de ANTIQORA',
    save: 'Guardar',
    cancel: 'Cancelar',
    reset: 'Restablecer ajustes',
    clearAll: 'Borrar todos los datos'
  },
  fr: {
    tagline: 'Comprendre le monde. Au-delà de la recherche.',
    searchPlaceholder: 'Recherchez à travers le Passé, le Présent et le Futur...',
    searchButton: 'Rechercher',
    allTab: 'Tout',
    websitesTab: 'Sites Web',
    appsTab: 'Applications',
    aiTab: 'Aperçu IA',
    timelineTab: 'Chronologie',
    futureTab: 'Intelligence Future',
    imagesTab: 'Images',
    videosTab: 'Vidéos',
    newsTab: 'Actualités',
    mapsTab: 'Lieux',
    shoppingTab: 'Achats',
    researchTab: 'Recherche',
    translateTab: 'Traduire',
    compareTab: 'Comparer',
    askAi: 'Poser une question de suivi',
    pastSection: 'PASSÉ : Fondation Historique',
    presentSection: 'PRÉSENT : Faits et Développements Actuels',
    futureSection: 'FUTUR : Tendances et Prévisions',
    demoNotice: 'Prototype Phase 1 : Démonstration de l’interface ANTIQORA.',
    settings: 'Paramètres',
    profile: 'Profil',
    appearance: 'Apparence',
    searchSettings: 'Paramètres de recherche',
    languageRegion: 'Langue et région',
    safeSearch: 'Recherche sécurisée',
    privacy: 'Confidentialité et données',
    notifications: 'Notifications',
    voiceSearch: 'Recherche vocale',
    aiSettings: 'Paramètres IA',
    searchResults: 'Résultats de recherche',
    accessibility: 'Accessibilité',
    appPwa: 'App et PWA',
    about: 'À propos d’ANTIQORA',
    save: 'Enregistrer',
    cancel: 'Annuler',
    reset: 'Réinitialiser les paramètres',
    clearAll: 'Effacer toutes les données'
  },
  de: {
    tagline: 'Die Welt verstehen. Jenseits der Suche.',
    searchPlaceholder: 'Suchen Sie über Vergangenheit, Gegenwart und Zukunft...',
    searchButton: 'Suchen',
    allTab: 'Alle',
    websitesTab: 'Websites',
    appsTab: 'Apps',
    aiTab: 'KI-Übersicht',
    timelineTab: 'Zeitleiste',
    futureTab: 'Zukunftsintelligenz',
    imagesTab: 'Bilder',
    videosTab: 'Videos',
    newsTab: 'Nachrichten',
    mapsTab: 'Orte',
    shoppingTab: 'Einkaufen',
    researchTab: 'Forschung',
    translateTab: 'Übersetzen',
    compareTab: 'Vergleichen',
    askAi: 'Folgefrage stellen',
    pastSection: 'VERGANGENHEIT: Historische Grundlagen',
    presentSection: 'GEGENWART: Aktuelle Fakten & Entwicklungen',
    futureSection: 'ZUKUNFT: Trends & Szenarien',
    demoNotice: 'Phase 1 Prototyp: ANTIQORA Suchoberflächen-Demonstration.',
    settings: 'Einstellungen',
    profile: 'Profil',
    appearance: 'Erscheinungsbild',
    searchSettings: 'Sucheinstellungen',
    languageRegion: 'Sprache & Region',
    safeSearch: 'Sichere Suche',
    privacy: 'Datenschutz & Daten',
    notifications: 'Benachrichtigungen',
    voiceSearch: 'Sprachsuche',
    aiSettings: 'KI-Einstellungen',
    searchResults: 'Suchergebnisse',
    accessibility: 'Barrierefreiheit',
    appPwa: 'App & PWA',
    about: 'Über ANTIQORA',
    save: 'Speichern',
    cancel: 'Abbrechen',
    reset: 'Einstellungen zurücksetzen',
    clearAll: 'Alle Daten löschen'
  },
  pt: {
    tagline: 'Compreenda o mundo. Além da busca.',
    searchPlaceholder: 'Pesquise através do Passado, Presente e Futuro...',
    searchButton: 'Pesquisar',
    allTab: 'Tudo',
    websitesTab: 'Sites',
    appsTab: 'Aplicativos',
    aiTab: 'Visão Geral IA',
    timelineTab: 'Linha do Tempo',
    futureTab: 'Inteligência Futura',
    imagesTab: 'Imagens',
    videosTab: 'Vídeos',
    newsTab: 'Notícias',
    mapsTab: 'Lugares',
    shoppingTab: 'Compras',
    researchTab: 'Pesquisa',
    translateTab: 'Traduzir',
    compareTab: 'Comparar',
    askAi: 'Fazer pergunta',
    pastSection: 'PASSADO: Fundação Histórica',
    presentSection: 'PRESENTE: Fatos e Notícias',
    futureSection: 'FUTURO: Tendências e Projeções',
    demoNotice: 'Protótipo Fase 1: Interface de pesquisa ANTIQORA.',
    settings: 'Configurações',
    profile: 'Perfil',
    appearance: 'Aparência',
    searchSettings: 'Configurações de busca',
    languageRegion: 'Idioma e região',
    safeSearch: 'Busca segura',
    privacy: 'Privacidade e dados',
    notifications: 'Notificações',
    voiceSearch: 'Busca por voz',
    aiSettings: 'Configurações de IA',
    searchResults: 'Resultados de busca',
    accessibility: 'Acessibilidade',
    appPwa: 'Aplicativo e PWA',
    about: 'Sobre o ANTIQORA',
    save: 'Salvar',
    cancel: 'Cancelar',
    reset: 'Redefinir configurações',
    clearAll: 'Limpar todos os dados'
  },
  ar: {
    tagline: 'افهم العالم. ما وراء البحث.',
    searchPlaceholder: 'ابحث في الماضي والحاضر والمستقبل...',
    searchButton: 'بحث',
    allTab: 'الكل',
    websitesTab: 'مواقع إلكترونية',
    appsTab: 'تطبيقات',
    aiTab: 'نظرة عامة بالذكاء الاصطناعي',
    timelineTab: 'الخط الزمني',
    futureTab: 'استشراف المستقبل',
    imagesTab: 'صور',
    videosTab: 'فيديو',
    newsTab: 'أخبار',
    mapsTab: 'أماكن',
    shoppingTab: 'تسوق',
    researchTab: 'أبحاث',
    translateTab: 'ترجمة',
    compareTab: 'مقارنة',
    askAi: 'سؤال متابعة',
    pastSection: 'الماضي: الجذور التاريخية',
    presentSection: 'الحاضر: أحدث الحقائق والتطورات',
    futureSection: 'المستقبل: الاتجاهات والتوقعات',
    demoNotice: 'نموذج أولي للمرحلة 1: عرض واجهة بحث ANTIQORA.',
    settings: 'الإعدادات',
    profile: 'الملف الشخصي',
    appearance: 'المظهر',
    searchSettings: 'إعدادات البحث',
    languageRegion: 'اللغة والمنطقة',
    safeSearch: 'البحث الآمن',
    privacy: 'الخصوصية والبيانات',
    notifications: 'الإشعارات',
    voiceSearch: 'البحث الصوتي',
    aiSettings: 'إعدادات الذكاء الاصطناعي',
    searchResults: 'نتائج البحث',
    accessibility: 'إمكانية الوصول',
    appPwa: 'التطبيق و PWA',
    about: 'حول ANTIQORA',
    save: 'حفظ',
    cancel: 'إلغاء',
    reset: 'إعادة تعيين كافة الإعدادات',
    clearAll: 'مسح كافة البيانات'
  },
  zh: {
    tagline: '理解世界。超越搜索。',
    searchPlaceholder: '跨越过去、现在与未来探索任何知识...',
    searchButton: '搜索',
    allTab: '全部',
    websitesTab: '网站',
    appsTab: '应用',
    aiTab: 'AI 概览',
    timelineTab: '时间线',
    futureTab: '未来洞察',
    imagesTab: '图片',
    videosTab: '视频',
    newsTab: '新闻',
    mapsTab: '地点',
    shoppingTab: '购物',
    researchTab: '学术研究',
    translateTab: '翻译',
    compareTab: '对比分析',
    askAi: '追问',
    pastSection: '过去：历史渊源与重要里程碑',
    presentSection: '现在：实时事实与最新动态',
    futureSection: '未来：发展趋势与可能情景',
    demoNotice: '第一阶段原型：展示 ANTIQORA 下一代搜索界面。',
    settings: '设置',
    profile: '个人资料',
    appearance: '外观',
    searchSettings: '搜索设置',
    languageRegion: '语言与地区',
    safeSearch: '安全搜索',
    privacy: '隐私与数据',
    notifications: '通知',
    voiceSearch: '语音搜索',
    aiSettings: 'AI 设置',
    searchResults: '搜索结果',
    accessibility: '无障碍辅助',
    appPwa: '应用与 PWA',
    about: '关于 ANTIQORA',
    save: '保存',
    cancel: '取消',
    reset: '重置所有设置',
    clearAll: '清除所有数据'
  },
  ja: {
    tagline: '世界を理解する。検索を超えて。',
    searchPlaceholder: '過去・現在・未来にわたるあらゆる知識を探索...',
    searchButton: '検索',
    allTab: 'すべて',
    websitesTab: 'ウェブサイト',
    appsTab: 'アプリ',
    aiTab: 'AI 概要',
    timelineTab: 'タイムライン',
    futureTab: '未来予測インサイト',
    imagesTab: '画像',
    videosTab: '動画',
    newsTab: 'ニュース',
    mapsTab: 'マップ・場所',
    shoppingTab: 'ショッピング',
    researchTab: '学術リサーチ',
    translateTab: '翻訳',
    compareTab: '比較',
    askAi: 'フォローアップ質問',
    pastSection: '過去：歴史的背景と節目',
    presentSection: '現在：最新の事実と進展',
    futureSection: '未来：動向と予測シナリオ',
    demoNotice: 'フェーズ1プロトタイプ：ANTIQORA 検索UIデモ。',
    settings: '設定',
    profile: 'プロフィール',
    appearance: '外観',
    searchSettings: '検索設定',
    languageRegion: '言語と地域',
    safeSearch: 'セーフサーチ',
    privacy: 'プライバシーとデータ',
    notifications: '通知',
    voiceSearch: '音声検索',
    aiSettings: 'AI 設定',
    searchResults: '検索結果',
    accessibility: 'アクセシビリティ',
    appPwa: 'アプリと PWA',
    about: 'ANTIQORA について',
    save: '保存',
    cancel: 'キャンセル',
    reset: 'すべての設定をリセット',
    clearAll: 'すべてのデータを消去'
  },
  ko: {
    tagline: '세상을 이해하다. 검색 그 이상으로.',
    searchPlaceholder: '과거, 현재, 미래를 아우르는 지식을 검색하세요...',
    searchButton: '검색',
    allTab: '전체',
    websitesTab: '웹사이트',
    appsTab: '앱',
    aiTab: 'AI 개요',
    timelineTab: '타임라인',
    futureTab: '미래 예측',
    imagesTab: '이미지',
    videosTab: '동영상',
    newsTab: '뉴스',
    mapsTab: '장소',
    shoppingTab: '쇼핑',
    researchTab: '연구 논문',
    translateTab: '번역',
    compareTab: '비교',
    askAi: '후속 질문',
    pastSection: '과거: 역사적 토대',
    presentSection: '현재: 검증된 팩트',
    futureSection: '미래: 트렌드 및 시나리오',
    demoNotice: '1단계 프로토타입: ANTIQORA 검색 인터페이스 시연.',
    settings: '설정',
    profile: '프로필',
    appearance: '화면 테마',
    searchSettings: '검색 설정',
    languageRegion: '언어 및 지역',
    safeSearch: '세이프서치',
    privacy: '개인정보 및 데이터',
    notifications: '알림',
    voiceSearch: '음성 검색',
    aiSettings: 'AI 설정',
    searchResults: '검색 결과',
    accessibility: '접근성',
    appPwa: '앱 및 PWA',
    about: 'ANTIQORA 정보',
    save: '저장',
    cancel: '취소',
    reset: '모든 설정 초기화',
    clearAll: '모든 데이터 삭제'
  },
  ru: {
    tagline: 'Понимайте мир. За пределами обычного поиска.',
    searchPlaceholder: 'Ищите знания сквозь прошлое, настоящее и будущее...',
    searchButton: 'Поиск',
    allTab: 'Все',
    websitesTab: 'Сайты',
    appsTab: 'Приложения',
    aiTab: 'ИИ-обзор',
    timelineTab: 'Хронология',
    futureTab: 'Будущее',
    imagesTab: 'Изображения',
    videosTab: 'Видео',
    newsTab: 'Новости',
    mapsTab: 'Места',
    shoppingTab: 'Покупки',
    researchTab: 'Исследования',
    translateTab: 'Перевод',
    compareTab: 'Сравнение',
    askAi: 'Задать вопрос',
    pastSection: 'ПРОШЛОЕ: Исторический фундамент',
    presentSection: 'НАСТОЯЩЕЕ: Факты и динамика',
    futureSection: 'БУДУЩЕЕ: Тренды и сценарии',
    demoNotice: 'Прототип фазы 1: Демонстрация интерфейса поиска ANTIQORA.',
    settings: 'Настройки',
    profile: 'Профиль',
    appearance: 'Внешний вид',
    searchSettings: 'Параметры поиска',
    languageRegion: 'Язык и регион',
    safeSearch: 'Безопасный поиск',
    privacy: 'Конфиденциальность и данные',
    notifications: 'Уведомления',
    voiceSearch: 'Голосовой поиск',
    aiSettings: 'Настройки ИИ',
    searchResults: 'Результаты поиска',
    accessibility: 'Специальные возможности',
    appPwa: 'Приложение и PWA',
    about: 'О проекте ANTIQORA',
    save: 'Сохранить',
    cancel: 'Отмена',
    reset: 'Сбросить все настройки',
    clearAll: 'Очистить все данные'
  }
};

export function getUIText(lang: string, key: string): string {
  const table = UI_TRANSLATIONS[lang] || UI_TRANSLATIONS['en'];
  return table[key] || UI_TRANSLATIONS['en'][key] || key;
}
